import Link from 'next/link';
import type { ReactNode } from 'react';

export function Shell({ children, wide = false }: { children: ReactNode; wide?: boolean }) {
  return <div className="min-h-screen"><a href="#main-content" className="sr-only focus:not-sr-only focus:block focus:bg-green-500 focus:p-3 focus:text-green-950">Skip to content</a><header className="border-b border-[#203027] bg-[#0d1510]"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-5 py-5 sm:px-8"><Link href="/" className="flex items-center gap-2.5 text-xl font-bold tracking-tight no-underline"><span aria-hidden className="flex h-8 w-8 items-center justify-center rounded-lg bg-green-500 text-base text-green-950">H</span>Headcount<span className="text-green-500">.</span></Link><span className="rounded-full border border-[#2c4535] px-3 py-1.5 text-[10px] font-semibold tracking-wider text-[#95b5a1]"><span aria-hidden className="mr-1.5 text-green-400">●</span>BASE SEPOLIA</span></div></header><main id="main-content" className={`mx-auto px-5 py-9 sm:px-8 sm:py-14 ${wide ? 'max-w-6xl' : 'max-w-xl'}`}>{children}</main><footer className="mx-auto max-w-6xl border-t border-[#1b2b21] px-5 py-6 text-xs text-[#708377] sm:px-8"><div className="flex flex-wrap justify-between gap-3"><span>Make every guest count.</span><span>Testnet demo · Mock hUSDC · No real funds</span></div></footer></div>;
}
export function ErrorNotice({ message }: { message: string | null }) { return message ? <p role="alert" className="rounded-xl border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-200">{message}</p> : null; }
export function Loading({ text = 'Loading…' }: { text?: string }) { return <div role="status" className="card flex items-center gap-3 p-6 text-sm text-[#8da695]"><span aria-hidden className="h-4 w-4 animate-pulse rounded-full bg-green-500/50" />{text}</div>; }
export function ExplorerLink({ tx, children }: { tx: string | null; children: ReactNode }) { return tx && /^0x[0-9a-fA-F]{64}$/.test(tx) ? <a href={`https://sepolia.basescan.org/tx/${tx}`} target="_blank" rel="noopener noreferrer" className="text-sm text-green-400 hover:text-green-300">{children} ↗</a> : null; }
